### ISSUE TITLE
IdP blindness breaks enterprise use cases and should not be a requirement of WebID

### ISSUE THREAD

**Issue by timcappalli** [WICG/WebID#45]
Related issues: #27 

The inability to reason over which applications a user is accessing is incompatible with enterprise requirements, particularly from a security and auditing perspective. "Conditional access" – enterprise-driven access controls based on the user, device, application and permissions involved in an authentication or authorization - is a primary use case for enterprise IdPs, used for:
1. Requiring multi-factor and/or device auth when specific apps are visited
2. Managing consent between RPs in the case of OAuth 2.X
3. Blocking access to disallowed applications
4. Requiring authentication for some applications to occur on certain networks
5. Preventing OAuth phishing attacks by observing how applications are used within an ecosystem (critical for both consumer and enterprise IdPs)

Additionally, tracking which applications corporate accounts are used with is a table-stakes expectation for administrators, for auditing and security purposes.   

The consumer privacy value provided by IdP anti-tracking measures is clear and inarguable. At the same time, enterprises cannot keep their workforce and businesses safe in these scenarios without an enlightened IdP, and will refuse to adopt WebID if these services are unavailable. 

An option for user consent within browser-controlled UX to release the application identifier to the IdP, with the IdP denying access without the release, appears to be the way forward. As a first cut of text – "✅ idp.example.com can know that you’re signing into example.payportal.com."

**Comment by samuelgoto** [comment]
I think that's largely agreed upon.

In fact, I think a stronger version of this is generally agreed upon: we don't expect the [RP tracking problem](https://github.com/WICG/WebID#the-rp-tracking-problem) to be applicable within enterprise either. Ack?

It really comes down to finding a mechanism/device to partition consumers and enterprise/edu users so that a more permissive (rightfully) allowed for the latter doesn't get abused / creeped in for the former.

So, I believe, we agree on the requirement/premise/motivation, which I think is half of the way.

What we are looking for now, is an enumeration of possible solutions that prevent the abuse for consumers.

> An option for user consent within browser-controlled UX to release the application identifier to the IdP, with the IdP denying access without the release, appears to be the way forward. As a first cut of text – "✅ idp.example.com can know that you’re signing into example.payportal.com."

This is a valid alternative and worth exploring.

I still think this is more intrusive/disruptive for enterprises than it needs to be.

There are a couple of things that occurred to us:

1) Enterprises can [set up enterprise policies](https://github.com/WICG/WebID/blob/master/enterprises.md#enterprise-policies) to waive all of the WebID restrictions. 
2) For BYOD use cases, we are exploring a partitioning of browser profiles and a Web Platform API that kicks off a different browser profile that makes the separation between your consumer accounts and your enterprise accounts.

WDYT?

**Comment by samuelgoto** [comment]
I wrote this down here:

https://github.com/samuelgoto/WebID#enterprise

Will close. Feel free to re-open if you feel this isn't a satisfying answer.
